function rveResult = importFEData(filename)
%IMPORTFILE Import data from a text file
%  RVERESULT1 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  RVERESULT1 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  rveResult1 = importfile("C:\Users\hlche\Documents\Chalmers\Thesis\Justin_Cheung_Files\Planner_Random_Data_Generation\RVEResult\rveResult_1.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 08-Mar-2023 14:33:07

dataLines = [2, Inf];

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 20);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["time", "e11", "e22", "e33", "e12", "e13", "e23", "s11", "s22", "s33", "s12", "s13", "s23", "a11", "a22", "a33", "a12", "a13", "a23", "vf"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
rveResult = readtable(filename, opts);
end