function [vf, a11, a22, a33, a12, a13, a23] = importProp_FFT_log(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ANALYSIS169 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a string array.
%
%  ANALYSIS169 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  analysis169 = importfile("C:\Users\hlche\Desktop\analysis_169.log", [1, Inf]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 08-Apr-2023 11:46:07

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14"];
opts.SelectedVariableNames = ["VarName1", "VarName2", "VarName3"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["VarName1", "VarName2", "VarName3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName1", "VarName2", "VarName3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14"], "EmptyFieldRule", "auto");

% Import the data
importedTable = readmatrix(filename, opts);

vf = str2double(importedTable(strcmp(importedTable, "volume_fraction"),3));
a11 = str2double(importedTable(strcmp(importedTable, "orientation_11"),3));
a22 = str2double(importedTable(strcmp(importedTable, "orientation_22"),3));
a33 = str2double(importedTable(strcmp(importedTable, "orientation_33"),3));
a12 = str2double(importedTable(strcmp(importedTable, "orientation_12"),3));
a13 = str2double(importedTable(strcmp(importedTable, "orientation_13"),3));
a23 = str2double(importedTable(strcmp(importedTable, "orientation_23"),3));
end